# Generated by Django 5.1.6 on 2025-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_purchaseorder_purchaseorderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='reference',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reference_id',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
