# Generated by Django 5.1.6 on 2025-09-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_purchaseorder_grand_total_purchaseorder_tax_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='po',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='tax_amount',
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
