# Generated by Django 5.1.6 on 2025-09-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_purchaseorderline_hsn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
