# Generated by Django 5.1.6 on 2025-09-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_journalentry_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbill',
            name='state',
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='core.journalentry'),
        ),
    ]
