# Generated by Django 5.1.6 on 2025-09-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customerinvoice_customerinvoiceline_customerpayment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinvoice',
            options={'ordering': ['-issue_date', '-id']},
        ),
        migrations.RenameField(
            model_name='customerinvoice',
            old_name='invoice_date',
            new_name='issue_date',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry'),
        ),
    ]
