# Generated by Django 5.1.6 on 2025-09-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contact_city_contact_mobile_contact_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_from_portal', to='core.customerinvoice'),
        ),
    ]
